version: "3.9"

services:
  backend:
    container_name: cover-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL
      - PORT    
    restart: always